---

- set_fact: instance_default_file={{default_file | dirname}}/{{es_instance_name}}_{{default_file | basename}}
- set_fact: instance_init_script={{init_script | dirname }}/{{es_instance_name}}_{{init_script | basename}}
- set_fact: conf_dir={{ es_conf_dir }}/{{es_instance_name}}
- set_fact: plugin_dir={{ es_plugin_dir }}/{{es_instance_name}}
- set_fact: m_lock_enabled={{ es_config['bootstrap.mlockall'] is defined and es_config['bootstrap.mlockall'] == True }}

- debug: msg="Node configuration {{ es_config }} "

- name: Include optional user and group creation. 
  when: (es_user_id is defined) and (es_group_id is defined)
  include: elasticsearch-optional-user.yml

#- name: Include specific Elasticsearch
#  include: "elasticsearch-{{ansible_os_family}}.yml"

#Install OS specific elasticsearch - this can be abbreviated in version 2.0.0
- name: Include specific Elasticsearch
  include: elasticsearch-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Include specific Elasticsearch
  include: elasticsearch-RedHat.yml
  when: ansible_os_family == 'RedHat'
