---
# Configure Elasticsearch Node

#Create required directories
- name: Create Directories
  become: yes
  file: path={{ item }} state=directory owner={{ es_user }} group={{ es_group }}
  with_items:
    - "{{ es_pid_dir }}"
    - "{{ es_log_dir }}"
    - "{{ es_conf_dir }}"
    - "{{ es_data_dirs }}"

#Copy the config template
- name: Copy Configuration File
  become: yes
  template: src=elasticsearch.yml.j2 dest={{ es_conf_dir }}/elasticsearch.yml owner={{ es_user }} group={{ es_group }} mode=0644 force=yes
  register: system_change
  notify: restart elasticsearch

#Copy the default file
- name: Copy Default File
  become: yes
  template: src=elasticsearch.j2 dest={{ default_file }} mode=0644 force=yes
  notify: restart elasticsearch

#Copy the logging.yml
- name: Copy log4j2.properties File
  become: yes
  template: src={{es_config_log4j2}} dest={{ es_conf_dir }}/log4j2.properties owner={{ es_user }} group={{ es_group }} mode=0644 force=yes
  notify: restart elasticsearch

- name: Copy jvm.options File
  become: yes
  template: src=jvm.options.j2 dest={{ es_conf_dir }}/jvm.options owner={{ es_user }} group={{ es_group }} mode=0644 force=yes
  notify: restart elasticsearch
