---

- set_fact: java_state="present"

- set_fact: java_state="latest"
  when: update_java == true

- name: RedHat - Ensure Java is installed
  yum: name={{ java }} state={{java_state}}
  when: ansible_os_family == 'RedHat'
  
- name: Debian - Ensure Java is installed
  apt: name={{ java }} state={{java_state}} update_cache=yes force=yes
  when: ansible_os_family == 'Debian'

- command: java -version 2>&1 | grep OpenJDK
  register: open_jdk
  changed_when: false

- name: refresh the java ca-certificates
  command: /var/lib/dpkg/info/ca-certificates-java.postinst configure
  when: ansible_distribution == 'Ubuntu' and open_jdk.rc == 0