---
- name: check-parameters
  include: checkParameters.yml
- name: os-specific vars
  include_vars: "{{ansible_os_family}}.yml"
- include: java.yml
- include: elasticsearch.yml
- include: elasticsearch-config.yml
- include: elasticsearch-scripts.yml
  when: es_scripts
- include: elasticsearch-plugins.yml
  when: es_plugins is defined or es_plugins_reinstall
- include: elasticsearch-service.yml
- include: elasticsearch-templates.yml
  when: es_templates
- meta: flush_handlers