---
- name: os-specific vars
  include_vars: "{{ansible_os_family}}.yml"
  tags:
      - always

- name: check-set-parameters
  include: elasticsearch-parameters.yml
  tags:
      - always

- include: java.yml
  when: es_java_install
  tags:
      - java

- include: elasticsearch.yml
  tags:
      - install

- include: elasticsearch-config.yml
  tags:
      - config

- include: elasticsearch-scripts.yml
  when: es_scripts
  tags:
      - scripts

- include: elasticsearch-plugins.yml
  when: es_plugins is defined or es_plugins_reinstall
  tags:
      - plugins

  #We always execute xpack as we may need to remove features
- include: xpack/elasticsearch-xpack.yml
  tags:
      - xpack

- meta: flush_handlers

#Templates done after restart - handled by flushing the handlers. e.g. suppose user removes security on a running node and doesn't specify es_api_basic_auth_username and es_api_basic_auth_password.  The templates will subsequently not be removed if we don't wait for the node to restart.
- include: elasticsearch-template.yml
  when: es_templates
  tags:
      - templates

- name: Make sure elasticsearch is started
  service: name={{instance_init_script | basename}} state=started enabled=yes
  when: es_start_service

- name: Wait for elasticsearch to startup
  wait_for: host={{es_api_host}} port={{es_api_port}} delay=5 connect_timeout=1
  when: es_restarted is defined and es_restarted.changed and es_start_service

- name: activate-license
  include: ./xpack/security/elasticsearch-xpack-activation.yml
  when: es_start_service and es_enable_xpack and es_xpack_license is defined and es_xpack_license != ''

#perform security actions here now elasticsearch is started
- include: ./xpack/security/elasticsearch-security-native.yml
  when: es_start_service and (es_enable_xpack and '"security" in es_xpack_features') and ((es_users is defined and es_users.native is defined) or (es_roles is defined and es_roles.native is defined))
