
- name: restart elasticsearch
  service: name={{instance_init_script | basename}} state=restarted enabled=yes
  when: es_restart_on_change and es_start_service and not elasticsearch_started.changed and ((plugin_installed is defined and plugin_installed.changed) or elasticsearch_install.changed)
